f"{'parts': [{'path': 'queryMetadata.json', 'payload': '{\n  "formatVersion": "202502",\n  "computeEngineSettings": {},\n  "name": "DF_Market_Create_Sales",\n  "queryGroups": [],\n  "documentLocale": "en-US",\n  "queriesMetadata": {\n    "Sales": {\n      "queryId": "3c5f1d88-f580-4180-914c-3bb5339152eb",\n      "queryName": "Sales",\n      "loadEnabled": false\n    },\n    "Sales_DataDestination": {\n      "queryId": "2546a9e5-b17b-45cf-bd73-5a0df3863798",\n      "queryName": "Sales_DataDestination",\n      "isHidden": true,\n      "loadEnabled": false\n    }\n  },\n  "connections": [\n    {\n      "path": "Lakehouse",\n      "kind": "Lakehouse",\n      "connectionId": "{\\"ClusterId\\":\\"a6435c22-dff6-482b-b260-825a6657a1f7\\",\\"DatasourceId\\":\\"21cf7c6d-c501-4aa8-b6d2-9cbcf9d5996e\\"}"\n    }\n  ]\n}', 'payloadType': 'InlineBase64'}, {'path': 'mashup.pq', 'payload': '[StagingDefinition = [Kind = "FastCopy"]]\r\nsection Section1;\r\n[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "Sales_DataDestination", IsNewTarget = true], Settings = [Kind = "Manual", AllowCreation = true, ColumnSettings = [Mappings = {[SourceColumnName = "Date", DestinationColumnName = "Date"], [SourceColumnName = "StoreID", DestinationColumnName = "StoreID"], [SourceColumnName = "TransactionID", DestinationColumnName = "TransactionID"], [SourceColumnName = "TransactionType", DestinationColumnName = "TransactionType"], [SourceColumnName = "TimeInt", DestinationColumnName = "TimeInt"], [SourceColumnName = "ProductID", DestinationColumnName = "ProductID"], [SourceColumnName = "UnitPrice", DestinationColumnName = "UnitPrice"], [SourceColumnName = "Qty", DestinationColumnName = "Qty"], [SourceColumnName = "Amount", DestinationColumnName = "Amount"]}], DynamicSchema = true, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]\r\nshared Sales = let\r\n  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Date = _t, StoreID = _t, TransactionID = _t, ProductID = _t, UnitPrice = _t, Qty = _t, TimeInt = _t, TransactionType = _t, Amount = _t]),\r\n  #"Changed column type" = Table.TransformColumnTypes(Source, {{"Date", type date}, {"ProductID", Int64.Type}, {"TransactionID", Int64.Type}, {"StoreID", Int64.Type}, {"UnitPrice", Currency.Type}, {"Qty", Int64.Type}, {"TimeInt", Int64.Type}, {"Amount", Currency.Type}}),\r\n  #"Reordered columns" = Table.ReorderColumns(#"Changed column type", {"Date", "StoreID", "TransactionID", "TransactionType", "TimeInt", "ProductID", "UnitPrice", "Qty"})\r\nin\r\n  #"Reordered columns";\r\nshared Sales_DataDestination = let\r\n  Pattern = Lakehouse.Contents([CreateNavigationProperties = false, EnableFolding = false]),\r\n  Navigation_1 = Pattern{[workspaceId = "{thisworkspaceid}"]}[Data],\r\n  Navigation_2 = Navigation_1{[lakehouseId = "{lakehouseid}"]}[Data],\r\n  TableNavigation = Navigation_2{[Id = "Sales", ItemKind = "Table"]}?[Data]?\r\nin\r\n  TableNavigation;\r\n', 'payloadType': 'InlineBase64'}, {'path': '.platform', 'payload': '{\n  "$schema": "https://developer.microsoft.com/json-schemas/fabric/gitIntegration/platformProperties/2.0.0/schema.json",\n  "metadata": {\n    "type": "Dataflow",\n    "displayName": "DF_Market_Create_Sales"\n  },\n  "config": {\n    "version": "2.0",\n    "logicalId": "00000000-0000-0000-0000-000000000000"\n  }\n}', 'payloadType': 'InlineBase64'}]}"
